const PORTALS = {
	BASE: 'data-react-portal',
	MINICART: 'MINICART',
	MINIBASKET: 'MINIBASKET',
	RECENTLYVIEWED: 'RECENTLYVIEWED',
	RECOMMENDATIONS: 'RECOMMENDATIONS',
	NOTIFICATIONS: 'NOTIFICATIONS',
	LOADING: 'LOADING',
}
export default PORTALS