const ACTIONTYPES = {
	// GLOBAL
	TOGGLELOADING: "TOGGLELOADING",
	
	// NOTIFICATIONS
	SETNOTIFICATION: "SETNOTIFICATION",
	DISPLAYNOTIFICATION: "DISPLAYNOTIFICATION",
	HIDENOTIFICATION: "HIDENOTIFICATION",
	UNSETNOTIFICATION: "HIDENOTIFICATION",

	// CRUD
	CREATE: "CREATE",
	READ: "READ",
	UPDATE: "UPDATE",
	DELETE: "DELETE",
	ENABLE: "ENABLE",
	DISABLE: "DISABLE",
	
	// Portals
	ENABLEPORTAL: "ENABLEPORTAL",
	DISABLEPORTAL: "DISABLEPORTAL",
	
	// cart
	CARTUPDATE: "CARTUPDATE",
	CARTUPDATED: "CARTUPDATED",
	CARTPRODUCTADDED: "CARTPRODUCTADDED",
	CARTPRODUCTDELETED: "CARTPRODUCTDELETED",
	CARTCLEARED : "CARTCLEARED",

	// RECCOMENDATIONS
	RECUPDATE: "RECUPDATE",
	RECCLEAR: "RECCLEAR",
}

export default ACTIONTYPES